services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
      SECRET_KEY: ${SECRET_KEY}
      BASE_URL: ${BASE_URL}
      EMAIL_NOTIFICATIONS_ENABLED: ${EMAIL_NOTIFICATIONS_ENABLED}
      EMAIL_SENDER_NAME: ${EMAIL_SENDER_NAME}
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command: http flask_app:5000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - flask_app
    ports:
      - "4040:4040"

volumes:
  mysql_data:
