services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
      SECRET_KEY: ${SECRET_KEY}
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    depends_on:
      - flask_app
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: always

volumes:
  mysql_data:
